= Space: Point of No Return: Смешанное ВПИ
:stylesheet: ./asciidoctor-skins/css/dark.css
// dark.css
:sectnums:
:figure-caption!:
:table-caption!:
:imagesdir: ./images
// :figure-caption: Рисунок
:title-page:
:author: Teflon; Mr._Glitched
:revnumber: 1.1
:revdate: 26.06.2026
:version-label: Редакция
:toc-title: СОДЕРЖАНИЕ
//:title-logo-image: {imagesdir}/
:toc:
:toclevels: 3
:last-update-label: Последнее обновление


:sectnums!:
== ВВЕДЕНИЕ
:sectnums:

Добро пожаловать в космическое смешанное ВПИ (военно-политическую игру) `Space: Point of No Return`. Смешанное ВПИ подразумевает собой смесь ролеплейной составляющей (нечеткой, размытой, отыгрывание ролей) и калькуляторной (четкой, конкретной, математика решает).

== Дисклеймер

=== Срок действия редакции

Механики этой игры будут меняться со временем, с каждой редакцией этого документа. Редакция этого документа указана в начале как `Редакция <Номер редакции>, <дата>`, это и будет ориентиром актуальности документа.

=== Изменение механик

По мере прохождения игры правила и механики будут подстраиваться под реалии происходящих событий. Это нужно для того, чтобы механики соответствовали реальной игре и сохраняли интерес для игроков.

=== Базовые механики

Первая редакция описывает лишь базовые механики, нужные для комфортного старта игры. По мере поступления проблем будут придумываться новые механики и изменяться старые.

=== Уточняйте информацию у администраторов или у вашего вердера

Этот документ -- неполный, правила все еще в разработке! Если у Вас возникли вопросы или Вы обнаружили неточности -- уточняйте информацию у администраторов или у Ваших вердеров! Это поможет дополнить правила и механики, чтобы уменьшить путаницу в будущем.

=== Как читать этот документ?

Этот документ читается сверху-вниз. Предполагается, что если Вы будете читать его последовательно, у Вас сложится общее представление об этом ВПИ, его механиках, и о том как правильно начать игру. Это не должно быть сложно, просто прочитайте до конца.


== Механики

=== Карта мира

Карта мира представляет собой карту галактики. Галактика поделена на звездные системы, каждая из которых имеет вокруг себя `зону владения`, то есть, владелец этой системы владеет и зоной вокруг нее в определенном радиусе.

=== Расы

Примеры рас: 

. Гуманоиды (к ним относятся люди, и им подобные).
. Членистоногие (насекомоподобные).
. Пернатые.
. Растениевидные.
. Машинный разум.

Раса может оказывать влияние на пригодность планет к заселению, на развитие государств, рост населения и т.д.

Игрок может указать расу в анкете регистрации, или администрация самостоятельно назначит её.

Раса может измениться со временем, при использовании генной инженерии, кибернетизации и т.д.

=== Валюта К — кредиты

Кредит (К) -- это условная общая игровая валюта, к которой сводятся все другие для удобства подсчета. Считайте ее просто абсолютной валютой.

1К -- это достаточно большое количество денег, с помощью которых можно неплохо развить конкретную отрасль или построить несколько кораблей (например 3 корвета).

Обозначение 1К или 4К -- это обозначение 1-го кредита или 4-ех кредитов соответственно (`К` здесь означает не тысячи единиц, а именно название валюты *КРЕДИТ!*).

=== Статистика

==== Бюджет

Бюджет изменяется от действий игрока. Он может как увеличиваться, так и сокращаться (выражается в количестве `К`). Также на бюджет влияют такие факторы как состояние экономики (рост, стагнация, кризис).

Бюджет пополняется за счет налоговой политики, государственных займов (как у внутренних, так и внешних кредиторов), за счет торговли, бизнеса, репараций и т.д.

Бюджет можно пополнить, включив «печатный станок», но это приведёт к скачку инфляции (вплоть до гиперинфляции).

==== Содержимое статистики

.Гражданская статистика
|===
| Рост ВВП | Уровень инфляции | Бюджет | Гос долг | Энергостанции | Зоны добычи | Звездные системы | Обитаемые планеты

| 10%
| 50%
| 100К
| 20К
| 2 штуки
| 3 штуки
| 2 системы
| 3 планеты

|===

.Статистика флота
|===
| Название корабля | Количество

| Корветы
| 2 единицы

|===

=== Торговля

Установление цены контракта:

Выглядит так так `X/10` (например, `3/10`).

- `1-3/10` -- это низкая цена;
- `4-7/10` -- это средняя цена;
- `8-10/10` -- это высокая цена.

Длительность контракта: Контракт может быть одноразовый или срочный.

Одноразовые контракты реализуются единоразово.

Сроки для срочного контракта указываются сторонами до даты из реальной жизни. После истечения срока контракта контракт перестаёт действовать (например, до 10 июля).

=== Присоединение систем

Новую систему можно присоединиться к себе если соблюдены следующие условия:

. Она не контролируется другим игроком.
. Она должна быть изучена с помощью исследовательского корабля.
. И в этой системе должна быть построена космическая база или оставлен радиомаяк.

Что такое космическая база?

Космическая база:: Специальная станция, которая будет размещена рядом с центром системы. Космическая база может содержать: центры обслуживания кораблей, торговые узлы, оборонные платформы (могут помочь при обороне системы). Примерная цена строительства будет составлять: 0,5К.

=== Система шпионажа

Вы можете построить агентурную сеть в цивилизации, с которой установлены дипломатические отношения. Успешность развития агентурной сети зависит от: дипломатических отношений, развития технологий, действия внутри цивилизации, в которой строится агентурная сеть.

=== Система ивентов

==== Внутренние ивенты

Ивенты внутри цивилизации обычно скрыты от глаз других цивилизаций; но если ивент слишком масштабный, то агентурная сеть других цивилизаций, торговые пути или внешнее наблюдение может сказать другим цивилизациям о том, что какой-то ивент происходит в Вашей цивилизации.

Внутренние ивенты обговариваются администраторами/вердерами с игроками на этих цивилизациях в скрытых чатах. Игрок отвечает, какие действия были предприняты в связи с ивентом.

==== Глобальные ивенты

Глобальные ивенты затрагивают сразу большую часть цивилизаций (возможно и всю галактику в целом). Их обычно сложно незаметить.

=== Ваша цивилизация

==== Создание цивилизации

Для создания своей цивилизации Вам нужно будет выбрать одну из звездных систем на карте, планету в ней, и придумать предысторию своей цивилизации.

==== Внутренняя политика

Внутренняя политика цивилизации подразумевает под собой:

- решение внутренних ивентов;
- экономическое развитие.

==== Внешняя политика

Внешняя политика цивилизации подразумевает под собой:

- решение внешних/глобальных ивентов;
- колонизация;
- взаимодействие с другими цивилизациями, будь то дипломатия или торговля.

=== Технологическое развитие

Уровни технологического развития, где 1 -- самый малый уровень развития, цивилизация только вышла в космос; чем больше число, тем выше технологическое развитие цивилизации. Например:

.Технологическое развитие
[cols=">1,<12"]
|===

| 1
| Базовые постройки и космические корабли (корветы и исследовательские корабли)

| 2
| Строительство фрегатов и планетарные системы ПВО и ПРО

| 3
| Строительство эсминцев и планетарные щиты

| 4
| Строительство крейсеров и 

| 5
| Строительство линкоров и добыча полезных ископаемых из газовых гигантов

| 6
| Строительство титанов и мегаструктуры

| ...
| ...

|===

Технология указывается в названии ЛК как последнее `-tr1`. Со временем развития государства и исследования новых технологий, оно будет получать тот или иной технологический уровень.

== Терминология

Редакция:: Вариант документа, выпущенный в определенную дату

ВПИ:: Военно-политическая игра. Игра, где вы управляете какой-либо цивилизацией на глобальной карте, чтобы достигать политических и военных целей

Смешанное ВПИ:: ВПИ с использованием ролевых (нечетких) механик в смеси с калькуляторными (четкими) механиками

Цивилизация:: Объединение, являющееся главным деятелем на глобальной карте

Механика:: Правило, по которому работает игра

Зона владения:: Территория в радиусе от звездной системы, которой владеет цивилизация, владеющая этой звездной системой

Агентурная сеть:: Сеть шпионов в цивилизации, принадлежащая другой цивилизации

Ивент:: Ролевое событие, происходящее в игре, и требующее действий со стороны игрока

Внутренний ивент:: Ивент внутри определённой цивилизации

Глобальный ивент:: Ивент, затрагивающий всю галактику или большую ее часть

ЛК:: Личный Канал для общения со своим вердером или админом. Здесь хранится статистика и отсюда управляется Ваша цивилизация

Космическая база:: Специальная станция, которая будет размещена рядом с центром системы. Космическая база может содержать: центры обслуживания кораблей, торговые узлы, оборонные платформы (могут помочь при обороне системы). Примерная цена строительства будет составлять: 0,5К

Кредит (К):: Условная общая игровая валюта, к которой сводятся все другие для удобства подсчета. Считайте ее просто абсолютной валютой

Контракт:: Контракт может быть одноразовым или срочным. Нужен для торговли
